StartupEvents.registry("creative_mode_tab", (e) => {
  e.create("industrial_revival")
    .icon(() =>
      Item.of(
        "custommachinery:custom_machine_item",
        '{machine:"custommachinery:industrialrevival/energetic_smelter"}'
      )
    )
    .content(() => [
      "kubejs:basic_machine_casing",
      Item.of(
        "custommachinery:custom_machine_item",
        '{machine:"custommachinery:industrialrevival/generator"}'
      ),
      Item.of(
        "custommachinery:custom_machine_item",
        '{machine:"custommachinery:industrialrevival/energetic_smelter"}'
      ),
      Item.of(
        "custommachinery:custom_machine_item",
        '{machine:"custommachinery:industrialrevival/compressor"}'
      ),
      Item.of(
        "custommachinery:custom_machine_item",
        '{machine:"custommachinery:industrialrevival/macerator"}'
      ),
      Item.of(
        "custommachinery:custom_machine_item",
        '{machine:"custommachinery:industrialrevival/alloy_foundry"}'
      ),
      Item.of(
        "custommachinery:custom_machine_item",
        '{machine:"custommachinery:industrialrevival/metal_former"}'
      ),
      Item.of(
        "custommachinery:custom_machine_item",
        '{machine:"custommachinery:industrialrevival/assembler"}'
      ),
      Item.of(
        "custommachinery:custom_machine_item",
        '{machine:"custommachinery:industrialrevival/rail_attacher"}'
      ),
      Item.of(
        "custommachinery:custom_machine_item",
        '{machine:"custommachinery:industrialrevival/fishing_basin"}'
      ),
      Item.of("custommachinery:configuration_card"),
    ]);
});
